apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pizza
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: pizza
        image: cssckb.azurecr.io/pizza:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: pizza
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pizza
